plugin:
  name: custom-data-type-link
  version: 1.0
  server:
    api-version:
      require: 1
  webfrontend:
    url: custom-data-type-link.js
    l10n: l10n/
custom_types:
  link:
    elasticsearch:
      mapping:
        type: object
        properties:
          url:
            type: string
            index: no
            fields:
              exact:
                type: string
                term_vector: with_positions_offsets
                analyzer: ez_exact_analyzer
              folded:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: ez_text_folded_analyzer
              fulltext:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: ez_text_fulltext_index_analyzer
                search_analyzer: ez_text_fulltext_search_analyzer
              sort:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: sort_de-DE
              suggest:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: ez_text_fulltext_index_analyzer
              token:
                type: string
                term_vector: with_positions_offsets
                analyzer: ez_text_token_analyzer
          text_plain:
            type: string
            index: no
            fields:
              exact:
                type: string
                term_vector: with_positions_offsets
                analyzer: ez_exact_analyzer
              folded:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: ez_text_folded_analyzer
              fulltext:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: ez_text_fulltext_index_analyzer
                search_analyzer: ez_text_fulltext_search_analyzer
              phrase:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: ez_text_phrase_index_analyzer
                search_analyzer: ez_text_fulltext_search_analyzer
              sort:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: sort_de-DE
              suggest:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: ez_text_suggest_analyzer
              token:
                type: string
                term_vector: with_positions_offsets
                analyzer: ez_text_token_analyzer
          tld:
            type: string
            index: no
            fields:
              exact:
                type: string
                term_vector: with_positions_offsets
                analyzer: ez_exact_analyzer
              folded:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: ez_text_folded_analyzer
              fulltext:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: ez_text_fulltext_index_analyzer
                search_analyzer: ez_text_fulltext_search_analyzer
              phrase:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: ez_text_phrase_index_analyzer
                search_analyzer: ez_text_fulltext_search_analyzer
              sort:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: sort_de-DE
              suggest:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: ez_text_suggest_analyzer
              token:
                type: string
                term_vector: with_positions_offsets
                analyzer: ez_text_token_analyzer
          text:
            type: object
            properties:
              de-DE:
                type: string
                index: no
                fields:
                  exact:
                    type: string
                    term_vector: with_positions_offsets
                    analyzer: ez_exact_analyzer
                  folded:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: ez_text_folded_analyzer
                  fulltext:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: ez_text_fulltext_index_analyzer
                    search_analyzer: ez_text_fulltext_search_analyzer
                  phrase:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: ez_text_phrase_index_analyzer
                    search_analyzer: ez_text_fulltext_search_analyzer
                  sort:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: sort_de-DE
                  suggest:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: ez_text_suggest_analyzer
                  token:
                    type: string
                    term_vector: with_positions_offsets
                    analyzer: ez_text_token_analyzer
              en-US:
                type: string
                index: no
                fields:
                  exact:
                    type: string
                    term_vector: with_positions_offsets
                    analyzer: ez_exact_analyzer
                  folded:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: ez_text_folded_analyzer
                  fulltext:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: ez_text_fulltext_index_analyzer
                    search_analyzer: ez_text_fulltext_search_analyzer
                  phrase:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: ez_text_phrase_index_analyzer
                    search_analyzer: ez_text_fulltext_search_analyzer
                  sort:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: sort_en-US
                  suggest:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: ez_text_suggest_analyzer
                  token:
                    type: string
                    term_vector: with_positions_offsets
                    analyzer: ez_text_token_analyzer
              es-ES:
                type: string
                index: no
                fields:
                  exact:
                    type: string
                    term_vector: with_positions_offsets
                    analyzer: ez_exact_analyzer
                  folded:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: ez_text_folded_analyzer
                  fulltext:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: ez_text_fulltext_index_analyzer
                    search_analyzer: ez_text_fulltext_search_analyzer
                  phrase:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: ez_text_phrase_index_analyzer
                    search_analyzer: ez_text_fulltext_search_analyzer
                  sort:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: sort_es-ES
                  suggest:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: ez_text_suggest_analyzer
                  token:
                    type: string
                    term_vector: with_positions_offsets
                    analyzer: ez_text_token_analyzer
              it-IT:
                type: string
                index: no
                fields:
                  exact:
                    type: string
                    term_vector: with_positions_offsets
                    analyzer: ez_exact_analyzer
                  folded:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: ez_text_folded_analyzer
                  fulltext:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: ez_text_fulltext_index_analyzer
                    search_analyzer: ez_text_fulltext_search_analyzer
                  phrase:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: ez_text_phrase_index_analyzer
                    search_analyzer: ez_text_fulltext_search_analyzer
                  sort:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: sort_it-IT
                  suggest:
                    type: string
                    term_vector: with_positions_offsets
                    index_analyzer: ez_text_suggest_analyzer
                  token:
                    type: string
                    term_vector: with_positions_offsets
                    analyzer: ez_text_token_analyzer
    config:
      schema:
        - name: title
          parameters:
            type:
              type: select
              options: ["none", "text", "text-l10n"]
        - name: add_timestamp
          parameters:
            value:
              type: bool
      mask:
        - name: editor_style
          parameters:
            value:
              type: select
              options: ["inline",  "popover"]
